name: Terraform & Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.6
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve
      env:
        TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Get EC2 Public IP
      working-directory: ./terraform
      run: |	
        echo "EC2_IP=$(terraform output -raw ec2_public_ip)"
        echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV


  deploy:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: SSH key setup
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to EC2
      run: |
        echo "EC2_IP:"
        echo "${{ env.EC2_IP }}"
        
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_IP << 'EOF'
        sudo apt-get update -y
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

        sudo apt-get update -y
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io

        sudo usermod -aG docker ubuntu
        sudo systemctl enable docker
        sudo systemctl start docker

        git clone https://github.com/kolesroma/cicd-web-app
        cd cicd-web-app/

        sudo docker build -t my-app .
        sudo docker run -d -p 80:80 --name my-running-app my-app
        EOF

